apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace: test-ns
  labels:
    app: nginxrs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxrs
  template:
    metadata:
      labels:
        app: nginxrs
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-servicers
  namespace: test-ns
spec:
  selector:
    app: nginxrs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
