apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/nginx-config" # Local path on the node
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/nginx-data" # Local path on the node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  namespace: chakri-ns
spec:
  selector:
    matchLabels:
      app: nginxtwo
  serviceName: nginx-servicetwo
  replicas: 3
  template:
    metadata:
      labels:
        app: nginxtwo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
  volumeClaimTemplates:
  - metadata:
      name: nginx-config-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi # Ensure storage matches PV capacity
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-servicetwo
  namespace: chakri-ns
spec:
  clusterIP: None
  selector:
    app: nginxtwo
  ports:
  - port: 80
    targetPort: 80
