apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  namespace: chakri-ns
  labels:
    app: nginxsf
spec:
  serviceName: nginx-service
  replicas: 2
  selector:
    matchLabels:
      app: nginxsf
  template:
    metadata:
      labels:
        app: nginxsf
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: nginx-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginxsf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

